// flow-typed signature: 99e5d4e1e1e58ba71fce0f4f16d3bb67
// flow-typed version: <<STUB>>/localforage_v^1.10.0/flow_v0.190.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'localforage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'localforage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'localforage/build/es5src/drivers/indexeddb' {
  declare module.exports: any;
}

declare module 'localforage/build/es5src/drivers/localstorage' {
  declare module.exports: any;
}

declare module 'localforage/build/es5src/drivers/websql' {
  declare module.exports: any;
}

declare module 'localforage/build/es5src/localforage' {
  declare module.exports: any;
}

declare module 'localforage/build/es5src/utils/serializer' {
  declare module.exports: any;
}

declare module 'localforage/dist/localforage' {
  declare module.exports: any;
}

declare module 'localforage/dist/localforage.min' {
  declare module.exports: any;
}

declare module 'localforage/dist/localforage.nopromises' {
  declare module.exports: any;
}

declare module 'localforage/dist/localforage.nopromises.min' {
  declare module.exports: any;
}

declare module 'localforage/src/drivers/indexeddb' {
  declare module.exports: any;
}

declare module 'localforage/src/drivers/localstorage' {
  declare module.exports: any;
}

declare module 'localforage/src/drivers/websql' {
  declare module.exports: any;
}

declare module 'localforage/src/localforage' {
  declare module.exports: any;
}

declare module 'localforage/src/utils/createBlob' {
  declare module.exports: any;
}

declare module 'localforage/src/utils/executeCallback' {
  declare module.exports: any;
}

declare module 'localforage/src/utils/executeTwoCallbacks' {
  declare module.exports: any;
}

declare module 'localforage/src/utils/getCallback' {
  declare module.exports: any;
}

declare module 'localforage/src/utils/idb' {
  declare module.exports: any;
}

declare module 'localforage/src/utils/includes' {
  declare module.exports: any;
}

declare module 'localforage/src/utils/isArray' {
  declare module.exports: any;
}

declare module 'localforage/src/utils/isIndexedDBValid' {
  declare module.exports: any;
}

declare module 'localforage/src/utils/isLocalStorageValid' {
  declare module.exports: any;
}

declare module 'localforage/src/utils/isWebSQLValid' {
  declare module.exports: any;
}

declare module 'localforage/src/utils/normalizeKey' {
  declare module.exports: any;
}

declare module 'localforage/src/utils/promise' {
  declare module.exports: any;
}

declare module 'localforage/src/utils/serializer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'localforage/build/es5src/drivers/indexeddb.js' {
  declare module.exports: $Exports<'localforage/build/es5src/drivers/indexeddb'>;
}
declare module 'localforage/build/es5src/drivers/localstorage.js' {
  declare module.exports: $Exports<'localforage/build/es5src/drivers/localstorage'>;
}
declare module 'localforage/build/es5src/drivers/websql.js' {
  declare module.exports: $Exports<'localforage/build/es5src/drivers/websql'>;
}
declare module 'localforage/build/es5src/localforage.js' {
  declare module.exports: $Exports<'localforage/build/es5src/localforage'>;
}
declare module 'localforage/build/es5src/utils/serializer.js' {
  declare module.exports: $Exports<'localforage/build/es5src/utils/serializer'>;
}
declare module 'localforage/dist/localforage.js' {
  declare module.exports: $Exports<'localforage/dist/localforage'>;
}
declare module 'localforage/dist/localforage.min.js' {
  declare module.exports: $Exports<'localforage/dist/localforage.min'>;
}
declare module 'localforage/dist/localforage.nopromises.js' {
  declare module.exports: $Exports<'localforage/dist/localforage.nopromises'>;
}
declare module 'localforage/dist/localforage.nopromises.min.js' {
  declare module.exports: $Exports<'localforage/dist/localforage.nopromises.min'>;
}
declare module 'localforage/src/drivers/indexeddb.js' {
  declare module.exports: $Exports<'localforage/src/drivers/indexeddb'>;
}
declare module 'localforage/src/drivers/localstorage.js' {
  declare module.exports: $Exports<'localforage/src/drivers/localstorage'>;
}
declare module 'localforage/src/drivers/websql.js' {
  declare module.exports: $Exports<'localforage/src/drivers/websql'>;
}
declare module 'localforage/src/localforage.js' {
  declare module.exports: $Exports<'localforage/src/localforage'>;
}
declare module 'localforage/src/utils/createBlob.js' {
  declare module.exports: $Exports<'localforage/src/utils/createBlob'>;
}
declare module 'localforage/src/utils/executeCallback.js' {
  declare module.exports: $Exports<'localforage/src/utils/executeCallback'>;
}
declare module 'localforage/src/utils/executeTwoCallbacks.js' {
  declare module.exports: $Exports<'localforage/src/utils/executeTwoCallbacks'>;
}
declare module 'localforage/src/utils/getCallback.js' {
  declare module.exports: $Exports<'localforage/src/utils/getCallback'>;
}
declare module 'localforage/src/utils/idb.js' {
  declare module.exports: $Exports<'localforage/src/utils/idb'>;
}
declare module 'localforage/src/utils/includes.js' {
  declare module.exports: $Exports<'localforage/src/utils/includes'>;
}
declare module 'localforage/src/utils/isArray.js' {
  declare module.exports: $Exports<'localforage/src/utils/isArray'>;
}
declare module 'localforage/src/utils/isIndexedDBValid.js' {
  declare module.exports: $Exports<'localforage/src/utils/isIndexedDBValid'>;
}
declare module 'localforage/src/utils/isLocalStorageValid.js' {
  declare module.exports: $Exports<'localforage/src/utils/isLocalStorageValid'>;
}
declare module 'localforage/src/utils/isWebSQLValid.js' {
  declare module.exports: $Exports<'localforage/src/utils/isWebSQLValid'>;
}
declare module 'localforage/src/utils/normalizeKey.js' {
  declare module.exports: $Exports<'localforage/src/utils/normalizeKey'>;
}
declare module 'localforage/src/utils/promise.js' {
  declare module.exports: $Exports<'localforage/src/utils/promise'>;
}
declare module 'localforage/src/utils/serializer.js' {
  declare module.exports: $Exports<'localforage/src/utils/serializer'>;
}
