// flow-typed signature: efaed8334fcfee6583c51099f1735ecb
// flow-typed version: <<STUB>>/sort-by_v^1.2.0/flow_v0.190.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sort-by'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sort-by' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sort-by/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sort-by/index' {
  declare module.exports: $Exports<'sort-by'>;
}
declare module 'sort-by/index.js' {
  declare module.exports: $Exports<'sort-by'>;
}
declare module 'sort-by/test/index' {
  declare module.exports: $Exports<'sort-by/test'>;
}
declare module 'sort-by/test/index.js' {
  declare module.exports: $Exports<'sort-by/test'>;
}
